/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientlist;

/**
 *
 * @author 2010304
 */
public class AddNewPatientDialog extends javax.swing.JDialog {
    // initialize instance variables to dialog object
    private String lastName;
    private String firstName;
    private int DOB;
    private String sex;
    private String race;
    private String maritalStatus;
    private int SSN;
    private int phoneNumber;
    private String street;
    private String city;
    private int zipCode;
    
    private boolean pressedOK = false;
    private String[] groupSex = {"000", "100"};
    private String[] groupRace = {"000", "100", "200", "300", "400", "500", "600"};
    private String[] groupMarital = {"000", "100", "200", "300"};
    
    public String getFirstName() {
        return firstName;
    }
    
    public String getLastName() {
        return lastName;
    }
    
    public int getDOB() {
        return DOB;
    }
    
    public String getSex() {
        return sex;
    }
    
    public String getStreet() {
        return street;
    }
    
    public String getCity() {
        return city;
    }
    
    public int getZipCode() {
        return zipCode;
    }
    
    public int getPhoneNumber() {
        return phoneNumber;
    }
    
    public int getSSN() {
        return SSN;
    }
    
    public String getRace() {
        return race;
    }
    
    public String getMaritalStatus() {
        return maritalStatus;
    }

    public boolean isPressedOK() {
        return pressedOK;
    }

    public String[] getGroupSex() {
        return groupSex;
    }
    
    public String[] getGroupRace() {
        return groupRace;
    }
    
    public String[] getGroupMarital() {
        return groupMarital;
    }

    /**
     * Creates new form AddNewPatientDialog
     */
    public AddNewPatientDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLast = new javax.swing.JLabel();
        labelFirst = new javax.swing.JLabel();
        textField_Last = new javax.swing.JTextField();
        textField_First = new javax.swing.JTextField();
        label_Birth = new javax.swing.JLabel();
        formattedTextField_Birth = new javax.swing.JFormattedTextField();
        label_Sex = new javax.swing.JLabel();
        comboBox_Sex = new javax.swing.JComboBox<>();
        label_Race = new javax.swing.JLabel();
        comboBox_Race = new javax.swing.JComboBox<>();
        label_Marital = new javax.swing.JLabel();
        comboBox_Marital = new javax.swing.JComboBox<>();
        label_SSN = new javax.swing.JLabel();
        formattedTextField_SSN = new javax.swing.JFormattedTextField();
        label_Phone = new javax.swing.JLabel();
        formattedTextField_Phone = new javax.swing.JFormattedTextField();
        label_Address = new javax.swing.JLabel();
        textField_Address = new javax.swing.JTextField();
        label_City = new javax.swing.JLabel();
        textField_City = new javax.swing.JTextField();
        label_City1 = new javax.swing.JLabel();
        formattedTextField_ZIP = new javax.swing.JFormattedTextField();
        button_OK = new javax.swing.JButton();
        button_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelLast.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLast.setText("Last Name:");

        labelFirst.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelFirst.setText("First Name:");

        label_Birth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_Birth.setText("Date of Birth:");

        formattedTextField_Birth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.LONG))));

        label_Sex.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_Sex.setText("Sex:");

        comboBox_Sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male\t", "Female" }));

        label_Race.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_Race.setText("Race:");

        comboBox_Race.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White\t", "Asian", "Black or African American", "Hispanic or Latino", "Native Hawaiian or Other Pacific Islander", "American Indian or Alaska Native", "Two or more races" }));

        label_Marital.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_Marital.setText("Marital Status:");

        comboBox_Marital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single ", "Married", "Widowed ", "Divorced", " " }));

        label_SSN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_SSN.setText("Social Security Number:");

        try {
            formattedTextField_SSN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### - ## - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        label_Phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_Phone.setText("Phone Number:");

        try {
            formattedTextField_Phone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### - ### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        label_Address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_Address.setText("Address:");

        label_City.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_City.setText("City:");

        label_City1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_City1.setText("ZIP Code:");

        formattedTextField_ZIP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        button_OK.setText("OK");
        button_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_OKActionPerformed(evt);
            }
        });

        button_Cancel.setText("Cancel");
        button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelLast)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textField_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_Birth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(formattedTextField_Birth)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Sex)
                            .addComponent(labelFirst))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField_First)
                            .addComponent(comboBox_Sex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Address)
                            .addComponent(label_City))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textField_City, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_City1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(formattedTextField_ZIP, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textField_Address)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(label_SSN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(formattedTextField_SSN))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_Race)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBox_Race, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_Marital)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBox_Marital, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_Phone)
                                .addGap(25, 25, 25)
                                .addComponent(formattedTextField_Phone))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLast)
                    .addComponent(labelFirst)
                    .addComponent(textField_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Birth)
                    .addComponent(formattedTextField_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Sex)
                    .addComponent(comboBox_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Race)
                    .addComponent(comboBox_Race, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Marital)
                    .addComponent(comboBox_Marital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_SSN)
                    .addComponent(formattedTextField_SSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Phone)
                    .addComponent(formattedTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_City)
                    .addComponent(textField_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_City1)
                    .addComponent(formattedTextField_ZIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_OK)
                    .addComponent(button_Cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_OKActionPerformed
        // TODO add your handling code here:
        pressedOK = true;
        
        // grab data from ui
        lastName = textField_Last.getText();
        firstName = textField_First.getText();
        DOB = Integer.parseInt(formattedTextField_Birth.getText());
        SSN = Integer.parseInt(formattedTextField_SSN.getText());
        phoneNumber = Integer.parseInt(formattedTextField_Phone.getText());
        sex = groupSex[comboBox_Sex.getSelectedIndex()];
        race = groupRace[comboBox_Race.getSelectedIndex()];
        maritalStatus = groupMarital[comboBox_Marital.getSelectedIndex()];
        
        // close the dialog
        this.setVisible(false);
    }//GEN-LAST:event_button_OKActionPerformed

    private void button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CancelActionPerformed
        // TODO add your handling code here:
        pressedOK = false;
        
        // grab data from ui
        lastName = "";
        firstName = "";
        sex = "";
        race = "";
        maritalStatus = "";
        
        // TODO figure out how to clear these textfields
        DOB = 0;
        SSN = 0;
        phoneNumber = 0;
        
        // close the dialog
        this.setVisible(false);
    }//GEN-LAST:event_button_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewPatientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewPatientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewPatientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewPatientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddNewPatientDialog dialog = new AddNewPatientDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Cancel;
    private javax.swing.JButton button_OK;
    private javax.swing.JComboBox<String> comboBox_Marital;
    private javax.swing.JComboBox<String> comboBox_Race;
    private javax.swing.JComboBox<String> comboBox_Sex;
    private javax.swing.JFormattedTextField formattedTextField_Birth;
    private javax.swing.JFormattedTextField formattedTextField_Phone;
    private javax.swing.JFormattedTextField formattedTextField_SSN;
    private javax.swing.JFormattedTextField formattedTextField_ZIP;
    private javax.swing.JLabel labelFirst;
    private javax.swing.JLabel labelLast;
    private javax.swing.JLabel label_Address;
    private javax.swing.JLabel label_Birth;
    private javax.swing.JLabel label_City;
    private javax.swing.JLabel label_City1;
    private javax.swing.JLabel label_Marital;
    private javax.swing.JLabel label_Phone;
    private javax.swing.JLabel label_Race;
    private javax.swing.JLabel label_SSN;
    private javax.swing.JLabel label_Sex;
    private javax.swing.JTextField textField_Address;
    private javax.swing.JTextField textField_City;
    private javax.swing.JTextField textField_First;
    private javax.swing.JTextField textField_Last;
    // End of variables declaration//GEN-END:variables
}
