/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientlist;


import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.io.Serializable;

/**
 *
 * @author 2010304
 */
public class PatientForm extends javax.swing.JFrame implements Serializable {
    
    // add an instance var ArrayList<Book> bookInventory
    ArrayList<Patient> patient = new ArrayList<Patient>();

    /**
     * Creates new form PatientForm
     */
    public PatientForm() {
        initComponents();
        
        // deserialize the data
        deserializeData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        panel_Search = new javax.swing.JPanel();
        checkBox_Last = new javax.swing.JCheckBox();
        textField_Last = new javax.swing.JTextField();
        checkBox_First = new javax.swing.JCheckBox();
        textField_First = new javax.swing.JTextField();
        checkBox_Sex = new javax.swing.JCheckBox();
        checkBox_Race = new javax.swing.JCheckBox();
        comboBox_Sex = new javax.swing.JComboBox<>();
        checkBox_Marital = new javax.swing.JCheckBox();
        comboBox_Marital = new javax.swing.JComboBox<>();
        comboBox_Race = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSearch = new javax.swing.JList<>();
        button_Search = new javax.swing.JButton();
        label_First = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textField_FirstName = new javax.swing.JTextField();
        textField_LastName = new javax.swing.JTextField();
        label_First1 = new javax.swing.JLabel();
        textField_DisplaySex = new javax.swing.JTextField();
        label_First2 = new javax.swing.JLabel();
        textField_DisplaySex1 = new javax.swing.JTextField();
        label_First3 = new javax.swing.JLabel();
        textField_DisplaySex2 = new javax.swing.JTextField();
        label_First4 = new javax.swing.JLabel();
        textField_DisplaySex3 = new javax.swing.JTextField();
        label_First5 = new javax.swing.JLabel();
        textField_DisplaySex4 = new javax.swing.JTextField();
        menuBar_Patient = new javax.swing.JMenuBar();
        menu_File = new javax.swing.JMenu();
        menuItem_New = new javax.swing.JMenuItem();
        menuItem_View = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItem_Exit = new javax.swing.JMenuItem();
        menu_Edit = new javax.swing.JMenu();
        menuItem_Edit = new javax.swing.JMenuItem();
        menuItem_Delete = new javax.swing.JMenuItem();
        menuItem_Clear = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_Search.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        checkBox_Last.setText("By Last Name");

        checkBox_First.setText("By First Name");
        checkBox_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_FirstActionPerformed(evt);
            }
        });

        checkBox_Sex.setText("By Sex");
        checkBox_Sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_SexActionPerformed(evt);
            }
        });

        checkBox_Race.setText("By  Race");
        checkBox_Race.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_RaceActionPerformed(evt);
            }
        });

        comboBox_Sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male\t", "Female" }));

        checkBox_Marital.setText("By  Marital Status");
        checkBox_Marital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_MaritalActionPerformed(evt);
            }
        });

        comboBox_Marital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single ", "Married", "Widowed ", "Divorced", " " }));

        comboBox_Race.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White\t", "Asian", "Black or African American", "Hispanic or Latino", "Native Hawaiian or Other Pacific Islander", "American Indian or Alaska Native", "Two or more races" }));

        javax.swing.GroupLayout panel_SearchLayout = new javax.swing.GroupLayout(panel_Search);
        panel_Search.setLayout(panel_SearchLayout);
        panel_SearchLayout.setHorizontalGroup(
            panel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_SearchLayout.createSequentialGroup()
                        .addGroup(panel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBox_Race)
                            .addComponent(checkBox_Marital))
                        .addGap(10, 10, 10)
                        .addGroup(panel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBox_Marital, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBox_Race, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_SearchLayout.createSequentialGroup()
                        .addGroup(panel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBox_First)
                            .addComponent(checkBox_Sex)
                            .addComponent(checkBox_Last))
                        .addGap(28, 28, 28)
                        .addGroup(panel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField_Last)
                            .addComponent(textField_First)
                            .addComponent(comboBox_Sex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panel_SearchLayout.setVerticalGroup(
            panel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SearchLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(panel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBox_Last)
                    .addComponent(textField_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBox_First)
                    .addComponent(textField_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBox_Sex)
                    .addComponent(comboBox_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBox_Race)
                    .addComponent(comboBox_Race, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBox_Marital)
                    .addComponent(comboBox_Marital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setViewportView(listSearch);

        button_Search.setText("Search");

        label_First.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_First.setText("First Name:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Last Name:");

        textField_FirstName.setEditable(false);

        textField_LastName.setEditable(false);

        label_First1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_First1.setText("Sex:");

        textField_DisplaySex.setEditable(false);

        label_First2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_First2.setText("Date Of Birth:");

        textField_DisplaySex1.setEditable(false);

        label_First3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_First3.setText("Address:");

        textField_DisplaySex2.setEditable(false);

        label_First4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_First4.setText("City:");

        textField_DisplaySex3.setEditable(false);

        label_First5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_First5.setText("ZIP Code:");

        textField_DisplaySex4.setEditable(false);

        menu_File.setText("File");

        menuItem_New.setText("Add New Patient");
        menuItem_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_NewActionPerformed(evt);
            }
        });
        menu_File.add(menuItem_New);

        menuItem_View.setText("View All Patients");
        menuItem_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_ViewActionPerformed(evt);
            }
        });
        menu_File.add(menuItem_View);
        menu_File.add(jSeparator1);

        menuItem_Exit.setText("Exit");
        menu_File.add(menuItem_Exit);

        menuBar_Patient.add(menu_File);

        menu_Edit.setText("Edit");

        menuItem_Edit.setText("Edit Existing Patient");
        menu_Edit.add(menuItem_Edit);

        menuItem_Delete.setText("Delete Patient");
        menu_Edit.add(menuItem_Delete);

        menuItem_Clear.setText("Clear Database");
        menu_Edit.add(menuItem_Clear);

        menuBar_Patient.add(menu_Edit);

        setJMenuBar(menuBar_Patient);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_Search, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_First)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(textField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_First1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textField_DisplaySex, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_First2)
                            .addComponent(label_First4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textField_DisplaySex3, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(textField_DisplaySex1))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_First3)
                            .addComponent(label_First5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField_DisplaySex2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textField_DisplaySex4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_First1)
                    .addComponent(textField_DisplaySex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_First))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_First2)
                    .addComponent(textField_DisplaySex1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_First3)
                    .addComponent(textField_DisplaySex2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_First4)
                    .addComponent(textField_DisplaySex3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_First5)
                    .addComponent(textField_DisplaySex4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_Search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBox_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_FirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_FirstActionPerformed

    private void checkBox_SexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_SexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_SexActionPerformed

    private void checkBox_RaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_RaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_RaceActionPerformed

    private void checkBox_MaritalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_MaritalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_MaritalActionPerformed

    private void menuItem_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_NewActionPerformed
        // TODO add your handling code here:
        
        //create an instance of the add new book dialog
        AddNewPatientDialog addDlg = new AddNewPatientDialog(this, true);
        // display the dialog
        addDlg.setVisible(true);
        
        //if pressedOK display title to list box
        if(addDlg.isPressedOK()) {
            // get the data from add dialog
            String fn = addDlg.getFirstName();
            String ln = addDlg.getLastName();
            String sx = addDlg.getSex();
            String st = addDlg.getStreet(); 
            int d = addDlg.getDOB();
            String c = addDlg.getCity();
            int z = addDlg.getZipCode();
            int p = addDlg.getPhoneNumber();
            int sn = addDlg.getSSN();
            String r = addDlg.getRace();
            String m = addDlg.getMaritalStatus();
            
            // create an instance of book object
            
            // serizalize the bookInventory
            serializeData();
        }
    }//GEN-LAST:event_menuItem_NewActionPerformed

    private void menuItem_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_ViewActionPerformed
        // TODO add your handling code here:
        
        // warning message example
        JOptionPane.showMessageDialog(null, 
                              "ALERT MESSAGE", 
                              "TITLE", 
                              JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_menuItem_ViewActionPerformed

    
        // add serialize and deserialize methods to the application
    private void serializeData() {
        try {
            FileOutputStream fileOut =
            new FileOutputStream("patient.dat");
            // here is where we are writing the entire array list
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            out.writeObject(patient);
            out.close();
            fileOut.close();
            System.out.printf("Serialized data is saved in patient.dat");
            } catch (IOException i) {
            i.printStackTrace();
        }
    }
    
    private void deserializeData() {
        try {
            FileInputStream fileIn = new FileInputStream("patient.dat");
            ObjectInputStream in = new ObjectInputStream(fileIn);
            // deserialize and cast to ArrayList<Book> type
            // assign to bookInventory var
            patient = (ArrayList<Patient>) in.readObject();
            in.close();
            fileIn.close();
        } catch (IOException i) {
            i.printStackTrace();
            return;
        } catch (ClassNotFoundException c) {
            System.out.println("patient class not found");
            c.printStackTrace();
            return;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Search;
    private javax.swing.JCheckBox checkBox_First;
    private javax.swing.JCheckBox checkBox_Last;
    private javax.swing.JCheckBox checkBox_Marital;
    private javax.swing.JCheckBox checkBox_Race;
    private javax.swing.JCheckBox checkBox_Sex;
    private javax.swing.JComboBox<String> comboBox_Marital;
    private javax.swing.JComboBox<String> comboBox_Race;
    private javax.swing.JComboBox<String> comboBox_Sex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel label_First;
    private javax.swing.JLabel label_First1;
    private javax.swing.JLabel label_First2;
    private javax.swing.JLabel label_First3;
    private javax.swing.JLabel label_First4;
    private javax.swing.JLabel label_First5;
    private javax.swing.JList<String> listSearch;
    private javax.swing.JMenuBar menuBar_Patient;
    private javax.swing.JMenuItem menuItem_Clear;
    private javax.swing.JMenuItem menuItem_Delete;
    private javax.swing.JMenuItem menuItem_Edit;
    private javax.swing.JMenuItem menuItem_Exit;
    private javax.swing.JMenuItem menuItem_New;
    private javax.swing.JMenuItem menuItem_View;
    private javax.swing.JMenu menu_Edit;
    private javax.swing.JMenu menu_File;
    private javax.swing.JPanel panel_Search;
    private javax.swing.JTextField textField_DisplaySex;
    private javax.swing.JTextField textField_DisplaySex1;
    private javax.swing.JTextField textField_DisplaySex2;
    private javax.swing.JTextField textField_DisplaySex3;
    private javax.swing.JTextField textField_DisplaySex4;
    private javax.swing.JTextField textField_First;
    private javax.swing.JTextField textField_FirstName;
    private javax.swing.JTextField textField_Last;
    private javax.swing.JTextField textField_LastName;
    // End of variables declaration//GEN-END:variables
}
